// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kHtAvOFZwUkMCFVfTNrEe886UEqpRBk',
    appId: '1:269444678938:web:4976b6374529cddefa58a3',
    messagingSenderId: '269444678938',
    projectId: 'medical-45d6b',
    authDomain: 'medical-45d6b.firebaseapp.com',
    storageBucket: 'medical-45d6b.appspot.com',
    measurementId: 'G-9HWHS8MB3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTt5LTZq8xiJwG9MpcPDQ9FLz7pFZHUDw',
    appId: '1:269444678938:android:a44fba4d260a3cb7fa58a3',
    messagingSenderId: '269444678938',
    projectId: 'medical-45d6b',
    storageBucket: 'medical-45d6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyROslZULpD_NnJDiMfmKA-c9WoVjl3f4',
    appId: '1:269444678938:ios:6c4d1e54cd5f5998fa58a3',
    messagingSenderId: '269444678938',
    projectId: 'medical-45d6b',
    storageBucket: 'medical-45d6b.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyROslZULpD_NnJDiMfmKA-c9WoVjl3f4',
    appId: '1:269444678938:ios:6c4d1e54cd5f5998fa58a3',
    messagingSenderId: '269444678938',
    projectId: 'medical-45d6b',
    storageBucket: 'medical-45d6b.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1kHtAvOFZwUkMCFVfTNrEe886UEqpRBk',
    appId: '1:269444678938:web:cc700b8c3475cacdfa58a3',
    messagingSenderId: '269444678938',
    projectId: 'medical-45d6b',
    authDomain: 'medical-45d6b.firebaseapp.com',
    storageBucket: 'medical-45d6b.appspot.com',
    measurementId: 'G-L1M4KT3WSC',
  );

}