// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbXkjUiVQL69omIZicBdCd6WH2zyYhDs',
    appId: '1:594206292292:web:48fb2604339d7b78777f11',
    messagingSenderId: '594206292292',
    projectId: 'oldage-1408e',
    authDomain: 'oldage-1408e.firebaseapp.com',
    storageBucket: 'oldage-1408e.appspot.com',
    measurementId: 'G-DLC1FL5E0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvzE7n6n-cYYqK15HX9tJKffnzc5X7W0',
    appId: '1:594206292292:android:d972cef4f3527bd0777f11',
    messagingSenderId: '594206292292',
    projectId: 'oldage-1408e',
    storageBucket: 'oldage-1408e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWFlZzNIsmPheYfsC2XM0Y4-I3PTGw_4',
    appId: '1:594206292292:ios:b6a50c54b48fe8dc777f11',
    messagingSenderId: '594206292292',
    projectId: 'oldage-1408e',
    storageBucket: 'oldage-1408e.appspot.com',
    iosBundleId: 'com.example.dementia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWFlZzNIsmPheYfsC2XM0Y4-I3PTGw_4',
    appId: '1:594206292292:ios:b6a50c54b48fe8dc777f11',
    messagingSenderId: '594206292292',
    projectId: 'oldage-1408e',
    storageBucket: 'oldage-1408e.appspot.com',
    iosBundleId: 'com.example.dementia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbXkjUiVQL69omIZicBdCd6WH2zyYhDs',
    appId: '1:594206292292:web:1e9c3c39a1198ea8777f11',
    messagingSenderId: '594206292292',
    projectId: 'oldage-1408e',
    authDomain: 'oldage-1408e.firebaseapp.com',
    storageBucket: 'oldage-1408e.appspot.com',
    measurementId: 'G-V4BNLG0999',
  );
}
